apiVersion: v1
kind: Pod
metadata:
  name: web-static-2
  labels:
    role: myrole
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "nginx"
    effect: "NoExecute"

    