apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-certificate
  namespace: default
spec:
  secretName: example-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  # commonName: mikku.atulaman.site
  dnsNames:
  - mikku.atulaman.site
  - chiku.atulaman.site