version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/ || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy


  vector:
    image: timberio/vector:0.10.0-debian
    container_name: vector
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vector.toml:/etc/vector/vector.toml
    depends_on:
      elasticsearch:
        condition: service_healthy
      
  node-app:
    build: ./node-app
    container_name: node-app
    ports:
      - "8000:8000"
    depends_on:
      - vector