apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: my-post-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-container
        image: nginx